/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.dualibib.Fachlogik.Languageverwaltung;

/**
 *
 * @author Carina
 */
public class PropertyName {

    //Allgemein
    public static final String SUCHEFIELD = "SUCHEFIELD";
    
    //AccountBearbeitenPanel
    public static final String ACCOUNTBEARBEITENPANEL_VORNAMELABLE = "ACCOUNTBEARBEITENPANEL_VORNAMELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_STRASSELABLE = "ACCOUNTBEARBEITENPANEL_STRASSELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_PLZLABLE = "ACCOUNTBEARBEITENPANEL_PLZLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_PASSWORTLABLE = "ACCOUNTBEARBEITENPANEL_PASSWORTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_CHECKPASSWORTLABLE = "ACCOUNTBEARBEITENPANEL_CHECKPASSWORTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_NAMELABLE = "ACCOUNTBEARBEITENPANEL_NAMELABLE";
    public static final String ACCOUNTBEARBEITENPANEL_HAUSNUMMERLABLE = "ACCOUNTBEARBEITENPANEL_HAUSNUMMERLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_STADTLABLE = "ACCOUNTBEARBEITENPANEL_STADTLABLE";
    public static final String ACCOUNTBEARBEITENPANEL_MITARBEITERCHECKBOX = "ACCOUNTBEARBEITENPANEL_MITARBEITERCHECKBOX";
    public static final String ACCOUNTBEARBEITENPANEL_SAVEBUTTON = "ACCOUNTBEARBEITENPANEL_SAVEBUTTON";
    public static final String ACCOUNTBEARBEITENPANEL_MELDUNGTEXT = "meldungText";
    /**
     * verschiedene arten
     */
    //AccountsBearbeitenPanel
    public static final String ACCOUNTSBEARBEITENPANEL_SUCHEACCOUNTFIELD = "ACCOUNTSBEARBEITENPANEL_SUCHEACCOUNTFIELD";
    public static final String ACCOUNTSBEARBEITENPANEL_ANLEGENBUTTON = "ACCOUNTSBEARBEITENPANEL_ANLEGENBUTTON";
    public static final String ACCOUNTSBEARBEITENPANEL_BEARBEITENBUTTON = "ACCOUNTSBEARBEITENPANEL_BEARBEITENBUTTON";
    //AusleihenBearbeitenPanel
    public static final String AUSLEIHENBEARBEITENPANEL_ENTFERNENBUTTON = "AUSLEIHENBEARBEITENPANEL_ENTFERNENBUTTON";
    //AusleihenPanel
    public static final String AUSLEIHENPANEL_ENTFERNENBUTTON = "AUSLEIHENPANEL_ENTFERNENBUTTON";
    //HistoryPanel
    public static final String HISTORYPANEL_HISTORYSUCHEFIELD = "HISTORYPANEL_HISTORYSUCHEFIELD";
    public static final String HISTORYPANEL_KATEGORIELABLE = "HISTORYPANEL_KATEGORIELABLE";
    public static final String HISTORYPANEL_AUSWAEHLENBUTTON = "HISTORYPANEL_AUSWAEHLENBUTTON";
    //LoginPanel
    public static final String LOGINPANEL_MELDUNGTEXT = "meldungText";
    /**
     * verschiedene arten
     */
    public static final String LOGINPANEL_ACCOUNTLABEL = "LOGINPANEL_ACCOUNTLABEL";
    public static final String LOGINPANEL_ACCOUNTNAMEFIELD = "LOGINPANEL_ACCOUNTNAMEFIELD";
    public static final String LOGINPANEL_PASSWORDLABEL = "LOGINPANEL_PASSWORDLABEL";
    public static final String LOGINPANEL_PASSWORTFIELD = "LOGINPANEL_PASSWORTFIELD";
    public static final String LOGINPANEL_LOGINBUTTON = "LOGINPANEL_LOGINBUTTON";
    //OptionPanel
    public static final String OPTIONPANEL_OPTIONLABEL = "OPTIONPANEL_OPTIONLABEL";
    public static final String OPTIONPANEL_UEBERNEHMENBUTTON = "OPTIONPANEL_UEBERNEHMENBUTTON";
    //SelectPanel
    public static final String SELECTPANEL_NAMELABLE = "SELECTPANEL_NAMELABLE";
    public static final String SELECTPANEL_STATUSLABLE = "SELECTPANEL_STATUSLABLE";
    public static final String SELECTPANEL_BESCHREIBUNGLABLE = "SELECTPANEL_BESCHREIBUNGLABLE";
    public static final String SELECTPANEL_KATEGORIELABLE = "SELECTPANEL_KATEGORIELABLE";
    public static final String SELECTPANEL_GENRELABLE = "SELECTPANEL_GENRELABLE";
    public static final String SELECTPANEL_AUSLEIHENBUTTON = "SELECTPANEL_AUSLEIHENBUTTON";
    public static final String SELECTPANEL_INFOLABEL = "SELECTPANEL_INFOLABEL";
    public static final String SELECTPANEL_DATELABLE = "SELECTPANEL_DATELABLE";
    //SuchePanel
    public static final String SUCHEPANEL_KATEGORIELABLE = "SUCHEPANEL_KATEGORIELABLE";
    public static final String SUCHEPANEL_GENRELABLE = "SUCHEPANEL_GENRELABLE";
    public static final String SUCHEPANEL_SELECTBUTTON = "SUCHEPANEL_SELECTBUTTON";

}
